server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
#          update here
          uri: https://github.com/Jbank.onlineavatoDev-com/internet-banking-microservices-configurations.git
          search-paths: configuration
          default-label: main
